<a href="https://colab.research.google.com/github/Anjinhyoung/TIL-Today-I-Learned-/blob/main/1_%EB%84%98%ED%8C%8C%EC%9D%B4_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.Numpy
* 수학 , 과학 계산용 패키지
* 자료구조: ndarray, 파이썬의 list보다 속도가 빠르다, 적은 메모리를 사용


In [ ]:
!pip install numpy # 파이참에다 설치

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy

In [ ]:
numpy

<module 'numpy' from '/usr/local/lib/python3.9/dist-packages/numpy/__init__.py'>

In [ ]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.9/dist-packages/numpy/__init__.py'>

1-1. ndarray

In [ ]:
ndarr1 = np.array([1,2,3,4])
print(ndarr1)
print(type(ndarr1)) # numpy. ndarray  = n dimension array

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
list1 = [1, 2, 3, 4]
list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(list1)
print(list2)
print(type(list1))
print(type(list2))

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
<class 'list'>


In [ ]:
# 리스트를 ndarray로 변환하는 방법
ndarr1 = np.array(list1)
ndarr2 = np.array(list2)
print(ndarr1)
print(type(ndarr1))

print(ndarr2)
print(type(ndarr2))

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


### 1-2. ndarray data type
* ndarray는 list와 1개의 단일 데이터 타입만 허용 만약에 int들 중에 float가 있으면 float이 가장 큰 요소니깐 float으로 바꿈

In [ ]:
ndarr1 = np.array([1,2,3,4])

In [ ]:
ndarr1

array([1, 2, 3, 4])

In [ ]:
ndarr1 = np.array([1,2,3,3.14,4])

In [ ]:
ndarr1

array([1.  , 2.  , 3.  , 3.14, 4.  ])

In [ ]:
ndarr1 = np.array([1,2,3,3.14,4,True])

In [ ]:
ndarr1

array([1.  , 2.  , 3.  , 3.14, 4.  , 1.  ])

In [ ]:
bool(10)

True

In [ ]:
bool('')

False

In [ ]:
bool(0)

False

In [ ]:
bool("python")

True

In [ ]:
ndarr4 = np.array([1,2,3.14,4,True,'apple'])

In [ ]:
ndarr4

array(['1', '2', '3.14', '4', 'True', 'apple'], dtype='<U32')

In [ ]:
type(ndarr4[0])

numpy.str_

In [ ]:
ndarr1 = np.array([1,2,3,3.14,4], dtype=int)

In [ ]:
# ndarr4 = np.array([1,2,3.14,4,True,'apple'], dtype=int) 못바꾸

In [ ]:
ndarr5 = np.array([1,2,3.14,4,True,'1234'], dtype=int)
ndarr5

array([   1,    2,    3,    4,    1, 1234])

### 1-3. ndarray 슬라이싱

In [ ]:
ndarr1 = np.array(['😊','😂','🤣','❤️','😒'])
ndarr1.shape

(5,)

In [ ]:
# 인덱싱
print(ndarr1[0])
print(ndarr1[4])
print(ndarr1[-1])
print(ndarr1[-2])

😊
😒
😒
❤️


In [ ]:
# 슬라이싱
print(ndarr1[0:3])
print(ndarr1[2:])
print(ndarr1[:3])

['😊' '😂' '🤣']
['🤣' '❤️' '😒']
['😊' '😂' '🤣']


In [ ]:
ndarr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ndarr2d.shape

(3, 4)

In [ ]:
print(ndarr2d[0,2])
print(ndarr2d[0][2])
print(ndarr2d[2,1])

3
3
10


In [ ]:
# 0행을 가져오기
print(ndarr2d[0])
print(ndarr2d[0,])
print(ndarr2d[0,:])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [ ]:
# 0열을 가져오기
print(ndarr2d[:,0])

[1 5 9]


In [ ]:
print(ndarr2d[:2,:])
print(ndarr2d[:2,2:])

[[1 2 3 4]
 [5 6 7 8]]
[[3 4]
 [7 8]]


# 1-4. Fancy 인덱싱
* 범위가 아닌 특정 index의 집합의 선택하여 추출하고 싶을 때 사용

In [ ]:
ndarr1 = np.array([10,23,2,6,90,85,32,66,80])

In [ ]:
idx = [1,4,6]

In [ ]:
ndarr1[idx]

array([23, 90, 32])

In [ ]:
ndarr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
ndarr2d[[0,1],:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 1-5. Boolean 인덱싱
* 조건 필터링을 통하여 Boolean 값을 이용한 색인

In [ ]:
ndarr1 = np.array(['😊','😂','🤣','❤️','😒'])
selValue =   [True,True,False,False,True]

In [ ]:
ndarr1[selValue]

array(['😊', '😂', '😒'], dtype='<U2')

In [ ]:
# ndarr1[selValue] # 개수가 안 맞아서 false

In [ ]:
ndarr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
ndarr2d > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
ndarr2d < 7

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
ndarr2d[ndarr2d < 7] # 잘  알기

array([1, 2, 3, 4, 5, 6])

#2. 행렬 연산

# 2-1. 연산자

In [ ]:
a = np.array([[1,2,3],
             [2,3,4]])

b = np.array([[3,4,5],
             [1,2,3]])

In [ ]:
# 덧셈 연산
# shape가 같아야함
# 같은 포지션끼리 연산
a+b

array([[4, 6, 8],
       [3, 5, 7]])

In [ ]:
a = np.array([[1,2,3],
             [2,3,4]])

b = np.array([[3,4,5],
             [1,2,3]])

In [ ]:
# 뺄셈 연산
a-b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [ ]:
# 곱센 연산
a*b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [ ]:
# 나눗셈   연산
a//b

array([[0, 0, 0],
       [2, 1, 1]])

In [ ]:
# dot.product(행렬의 내적)
# 맞닿는 shape가 같아야 함
# 떨어져 있는 shape가 결과 행렬이 됨
a=np.array([[1,2,3],
            [1,2,3],
            [2,3,4]])

b=np.array([[1,2],
           [3,4],
           [5,6]])

In [ ]:
a.shape, b.shape

((3, 3), (3, 2))

In [ ]:
print((1*1 + 2*3 + 3*5),(1*2 + 2*4 + 3*6))
print((1*1 + 2*3 + 3*5),(1*2 + 2*4 + 3*6))
print((2*1+3*3+4*5), (2*2+3*4+4*6))

22 28
22 28
31 40


In [ ]:
np.dot(a,b)

array([[22, 28],
       [22, 28],
       [31, 40]])

### 2-2. arange
* 순차적인 값을 생성할 때 사용

In [ ]:
arr1 = range(1,11)

In [ ]:
arr1

range(1, 11)

In [ ]:
for i in arr1:
    print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 

In [ ]:
arr2 = range(1,11)

In [ ]:
arr2 = range(1,11)

In [ ]:
for i in arr2:
    print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 

### 2-3. sort

In [ ]:
ndarr1 = np.array([1,10,5,7,2,4,3,6,8,9])
ndarr1

array([ 1, 10,  5,  7,  2,  4,  3,  6,  8,  9])

In [ ]:
np.sort(ndarr1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ndarr1

array([ 1, 10,  5,  7,  2,  4,  3,  6,  8,  9])

In [ ]:
#np.sort(ndarr1,reverse=True) # reverse 속성이 없음

In [ ]:
np.sort(ndarr1)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
# 문자열 역순으로 출력하기
s='python'
print(s[::-1])

nohtyp


In [ ]:
ndarr2d = np.array([[11,10,12,9],
                    [3,1,4,2],
                    [5,6,7,8]])

In [ ]:
ndarr2d.shape

(3, 4)

In [ ]:
# 행 정렬
np.sort(ndarr2d,axis=0)

array([[ 3,  1,  4,  2],
       [ 5,  6,  7,  8],
       [11, 10, 12,  9]])

In [ ]:
# 열 정렬
np.sort(ndarr2d,axis=1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
# 축의 마지막 방향
np.sort(ndarr2d, axis=-1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

### 2-4.숫자의 단일 연산

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,3,3],[3,3,3]])

In [ ]:
!git clone https://Anjinhyoung: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@github.com/Anjinhyoung/TIL-Today-I-Learned-.git

Cloning into 'TIL-Today-I-Learned-'...
remote: Enumerating objects: 363, done.
remote: Counting objects: 100% (206/206), done.
remote: Compressing objects: 100% (151/151), done.
remote: Total 363 (delta 82), reused 21 (delta 21), pack-reused 157
Receiving objects: 100% (363/363), 87.44 KiB | 6.73 MiB/s, done.
Resolving deltas: 100% (85/85), done.


In [ ]:
!git clone https://github.com/Anjinhyoung/TIL-Today-I-Learned-.git

fatal: destination path 'TIL-Today-I-Learned-' already exists and is not an empty directory.
